### ISSUE TITLE
About account details' balance

### ISSUE THREAD

**Issue by samfeng0517** [portto/fcl-swift#22]
Hi, I want to get account's balance use `fcl.getAccount` with address I passed in. 
However, when I get the value back I found that balance's data type is `UInt64`, but the balance of that account is with decimal point, so I can't get the value directly.
Is there any method or function to let me get value with decimal point? Or I just have to parse it myself? 
Thanks.

**Comment by andrew54068** [comment]
Short answer: you should handle it by your self.

Long one: Since the value you get from flow blockchain is expressed by the smallest unit of flow which is 0.00000001 in decimal. You should convert to whatever type you want to use, such as BigInt or Decimal. Another approach is to use script to query balance using script below.

```
import FlowToken from 0xFLOW_TOKEN_ADDRESS
import FungibleToken from 0xFUNGIBLE_TOKEN_ADDRESS

pub fun main(address: Address): UFix64 {
  let flowValutRef = getAccount(address)
    .getCapability<&FlowToken.Vault{FungibleToken.Balance}>(/public/flowTokenBalance)
    .borrow() ?? panic("Could not borrow a reference to the Flow token receiver capability")
  return flowValutRef.balance
}
```

And the result type `UFix64` can be converted by https://github.com/portto/fcl-swift/blob/49711cb6b1dfa6f479d95d9eeb5b39b575faec1a/Demo/FCL_Cocoa_Demo/FCL_Cocoa_Demo/FlowDemoViewController.swift#L894-L895
then you have the decimal type you want.
